
namespace QR_Code_Generator
{
    partial class VCardPanel
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(VCardPanel));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.lblFirstName = new System.Windows.Forms.Label();
            this.txtFirstName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblLastName = new System.Windows.Forms.Label();
            this.txtLastName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtOrgTitle = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblOrganizationTitle = new System.Windows.Forms.Label();
            this.txtOrganization = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblOrganization = new System.Windows.Forms.Label();
            this.txtWebsite = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblWebsite = new System.Windows.Forms.Label();
            this.txtEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblEmail = new System.Windows.Forms.Label();
            this.txtPhonePrivate = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblPhonePrivate = new System.Windows.Forms.Label();
            this.txtPhoneWork = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblPhoneWork = new System.Windows.Forms.Label();
            this.txtZipcode = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblZipcode = new System.Windows.Forms.Label();
            this.txtCity = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblCity = new System.Windows.Forms.Label();
            this.txtStreet = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblStreet = new System.Windows.Forms.Label();
            this.txtCountry = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblCountry = new System.Windows.Forms.Label();
            this.SuspendLayout();
            // 
            // lblFirstName
            // 
            this.lblFirstName.AutoSize = true;
            this.lblFirstName.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblFirstName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(140)))), ((int)(((byte)(140)))), ((int)(((byte)(140)))));
            this.lblFirstName.Location = new System.Drawing.Point(29, 25);
            this.lblFirstName.Name = "lblFirstName";
            this.lblFirstName.Size = new System.Drawing.Size(96, 20);
            this.lblFirstName.TabIndex = 2;
            this.lblFirstName.Text = "First Name";
            // 
            // txtFirstName
            // 
            this.txtFirstName.AcceptsReturn = false;
            this.txtFirstName.AcceptsTab = false;
            this.txtFirstName.AnimationSpeed = 200;
            this.txtFirstName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtFirstName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtFirstName.AutoSizeHeight = true;
            this.txtFirstName.BackColor = System.Drawing.Color.Transparent;
            this.txtFirstName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtFirstName.BackgroundImage")));
            this.txtFirstName.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            this.txtFirstName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtFirstName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            this.txtFirstName.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            this.txtFirstName.BorderRadius = 30;
            this.txtFirstName.BorderThickness = 2;
            this.txtFirstName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtFirstName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFirstName.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtFirstName.DefaultText = "";
            this.txtFirstName.FillColor = System.Drawing.Color.White;
            this.txtFirstName.HideSelection = true;
            this.txtFirstName.IconLeft = null;
            this.txtFirstName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFirstName.IconPadding = 10;
            this.txtFirstName.IconRight = null;
            this.txtFirstName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFirstName.Lines = new string[0];
            this.txtFirstName.Location = new System.Drawing.Point(29, 55);
            this.txtFirstName.MaxLength = 32767;
            this.txtFirstName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtFirstName.Modified = false;
            this.txtFirstName.Multiline = false;
            this.txtFirstName.Name = "txtFirstName";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFirstName.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtFirstName.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFirstName.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFirstName.OnIdleState = stateProperties4;
            this.txtFirstName.Padding = new System.Windows.Forms.Padding(3);
            this.txtFirstName.PasswordChar = '\0';
            this.txtFirstName.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtFirstName.PlaceholderText = "";
            this.txtFirstName.ReadOnly = false;
            this.txtFirstName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtFirstName.SelectedText = "";
            this.txtFirstName.SelectionLength = 0;
            this.txtFirstName.SelectionStart = 0;
            this.txtFirstName.ShortcutsEnabled = true;
            this.txtFirstName.Size = new System.Drawing.Size(300, 40);
            this.txtFirstName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtFirstName.TabIndex = 3;
            this.txtFirstName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtFirstName.TextMarginBottom = 0;
            this.txtFirstName.TextMarginLeft = 3;
            this.txtFirstName.TextMarginTop = 1;
            this.txtFirstName.TextPlaceholder = "";
            this.txtFirstName.UseSystemPasswordChar = false;
            this.txtFirstName.WordWrap = true;
            // 
            // lblLastName
            // 
            this.lblLastName.AutoSize = true;
            this.lblLastName.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblLastName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(140)))), ((int)(((byte)(140)))), ((int)(((byte)(140)))));
            this.lblLastName.Location = new System.Drawing.Point(371, 25);
            this.lblLastName.Name = "lblLastName";
            this.lblLastName.Size = new System.Drawing.Size(95, 20);
            this.lblLastName.TabIndex = 4;
            this.lblLastName.Text = "Last Name";
            // 
            // txtLastName
            // 
            this.txtLastName.AcceptsReturn = false;
            this.txtLastName.AcceptsTab = false;
            this.txtLastName.AnimationSpeed = 200;
            this.txtLastName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtLastName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtLastName.AutoSizeHeight = true;
            this.txtLastName.BackColor = System.Drawing.Color.Transparent;
            this.txtLastName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtLastName.BackgroundImage")));
            this.txtLastName.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            this.txtLastName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtLastName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            this.txtLastName.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            this.txtLastName.BorderRadius = 30;
            this.txtLastName.BorderThickness = 2;
            this.txtLastName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtLastName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLastName.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtLastName.DefaultText = "";
            this.txtLastName.FillColor = System.Drawing.Color.White;
            this.txtLastName.HideSelection = true;
            this.txtLastName.IconLeft = null;
            this.txtLastName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLastName.IconPadding = 10;
            this.txtLastName.IconRight = null;
            this.txtLastName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLastName.Lines = new string[0];
            this.txtLastName.Location = new System.Drawing.Point(371, 55);
            this.txtLastName.MaxLength = 32767;
            this.txtLastName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtLastName.Modified = false;
            this.txtLastName.Multiline = false;
            this.txtLastName.Name = "txtLastName";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLastName.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtLastName.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLastName.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLastName.OnIdleState = stateProperties8;
            this.txtLastName.Padding = new System.Windows.Forms.Padding(3);
            this.txtLastName.PasswordChar = '\0';
            this.txtLastName.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtLastName.PlaceholderText = "";
            this.txtLastName.ReadOnly = false;
            this.txtLastName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtLastName.SelectedText = "";
            this.txtLastName.SelectionLength = 0;
            this.txtLastName.SelectionStart = 0;
            this.txtLastName.ShortcutsEnabled = true;
            this.txtLastName.Size = new System.Drawing.Size(300, 40);
            this.txtLastName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtLastName.TabIndex = 5;
            this.txtLastName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtLastName.TextMarginBottom = 0;
            this.txtLastName.TextMarginLeft = 3;
            this.txtLastName.TextMarginTop = 1;
            this.txtLastName.TextPlaceholder = "";
            this.txtLastName.UseSystemPasswordChar = false;
            this.txtLastName.WordWrap = true;
            // 
            // txtOrgTitle
            // 
            this.txtOrgTitle.AcceptsReturn = false;
            this.txtOrgTitle.AcceptsTab = false;
            this.txtOrgTitle.AnimationSpeed = 200;
            this.txtOrgTitle.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtOrgTitle.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtOrgTitle.AutoSizeHeight = true;
            this.txtOrgTitle.BackColor = System.Drawing.Color.Transparent;
            this.txtOrgTitle.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtOrgTitle.BackgroundImage")));
            this.txtOrgTitle.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            this.txtOrgTitle.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtOrgTitle.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            this.txtOrgTitle.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            this.txtOrgTitle.BorderRadius = 30;
            this.txtOrgTitle.BorderThickness = 2;
            this.txtOrgTitle.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtOrgTitle.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtOrgTitle.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtOrgTitle.DefaultText = "";
            this.txtOrgTitle.FillColor = System.Drawing.Color.White;
            this.txtOrgTitle.HideSelection = true;
            this.txtOrgTitle.IconLeft = null;
            this.txtOrgTitle.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtOrgTitle.IconPadding = 10;
            this.txtOrgTitle.IconRight = null;
            this.txtOrgTitle.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtOrgTitle.Lines = new string[0];
            this.txtOrgTitle.Location = new System.Drawing.Point(371, 140);
            this.txtOrgTitle.MaxLength = 32767;
            this.txtOrgTitle.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtOrgTitle.Modified = false;
            this.txtOrgTitle.Multiline = false;
            this.txtOrgTitle.Name = "txtOrgTitle";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtOrgTitle.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtOrgTitle.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtOrgTitle.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtOrgTitle.OnIdleState = stateProperties12;
            this.txtOrgTitle.Padding = new System.Windows.Forms.Padding(3);
            this.txtOrgTitle.PasswordChar = '\0';
            this.txtOrgTitle.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtOrgTitle.PlaceholderText = "";
            this.txtOrgTitle.ReadOnly = false;
            this.txtOrgTitle.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtOrgTitle.SelectedText = "";
            this.txtOrgTitle.SelectionLength = 0;
            this.txtOrgTitle.SelectionStart = 0;
            this.txtOrgTitle.ShortcutsEnabled = true;
            this.txtOrgTitle.Size = new System.Drawing.Size(300, 40);
            this.txtOrgTitle.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtOrgTitle.TabIndex = 9;
            this.txtOrgTitle.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtOrgTitle.TextMarginBottom = 0;
            this.txtOrgTitle.TextMarginLeft = 3;
            this.txtOrgTitle.TextMarginTop = 1;
            this.txtOrgTitle.TextPlaceholder = "";
            this.txtOrgTitle.UseSystemPasswordChar = false;
            this.txtOrgTitle.WordWrap = true;
            // 
            // lblOrganizationTitle
            // 
            this.lblOrganizationTitle.AutoSize = true;
            this.lblOrganizationTitle.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblOrganizationTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(140)))), ((int)(((byte)(140)))), ((int)(((byte)(140)))));
            this.lblOrganizationTitle.Location = new System.Drawing.Point(371, 110);
            this.lblOrganizationTitle.Name = "lblOrganizationTitle";
            this.lblOrganizationTitle.Size = new System.Drawing.Size(150, 20);
            this.lblOrganizationTitle.TabIndex = 8;
            this.lblOrganizationTitle.Text = "Organization Title";
            // 
            // txtOrganization
            // 
            this.txtOrganization.AcceptsReturn = false;
            this.txtOrganization.AcceptsTab = false;
            this.txtOrganization.AnimationSpeed = 200;
            this.txtOrganization.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtOrganization.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtOrganization.AutoSizeHeight = true;
            this.txtOrganization.BackColor = System.Drawing.Color.Transparent;
            this.txtOrganization.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtOrganization.BackgroundImage")));
            this.txtOrganization.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            this.txtOrganization.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtOrganization.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            this.txtOrganization.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            this.txtOrganization.BorderRadius = 30;
            this.txtOrganization.BorderThickness = 2;
            this.txtOrganization.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtOrganization.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtOrganization.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtOrganization.DefaultText = "";
            this.txtOrganization.FillColor = System.Drawing.Color.White;
            this.txtOrganization.HideSelection = true;
            this.txtOrganization.IconLeft = null;
            this.txtOrganization.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtOrganization.IconPadding = 10;
            this.txtOrganization.IconRight = null;
            this.txtOrganization.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtOrganization.Lines = new string[0];
            this.txtOrganization.Location = new System.Drawing.Point(29, 140);
            this.txtOrganization.MaxLength = 32767;
            this.txtOrganization.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtOrganization.Modified = false;
            this.txtOrganization.Multiline = false;
            this.txtOrganization.Name = "txtOrganization";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtOrganization.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtOrganization.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtOrganization.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtOrganization.OnIdleState = stateProperties16;
            this.txtOrganization.Padding = new System.Windows.Forms.Padding(3);
            this.txtOrganization.PasswordChar = '\0';
            this.txtOrganization.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtOrganization.PlaceholderText = "";
            this.txtOrganization.ReadOnly = false;
            this.txtOrganization.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtOrganization.SelectedText = "";
            this.txtOrganization.SelectionLength = 0;
            this.txtOrganization.SelectionStart = 0;
            this.txtOrganization.ShortcutsEnabled = true;
            this.txtOrganization.Size = new System.Drawing.Size(300, 40);
            this.txtOrganization.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtOrganization.TabIndex = 7;
            this.txtOrganization.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtOrganization.TextMarginBottom = 0;
            this.txtOrganization.TextMarginLeft = 3;
            this.txtOrganization.TextMarginTop = 1;
            this.txtOrganization.TextPlaceholder = "";
            this.txtOrganization.UseSystemPasswordChar = false;
            this.txtOrganization.WordWrap = true;
            // 
            // lblOrganization
            // 
            this.lblOrganization.AutoSize = true;
            this.lblOrganization.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblOrganization.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(140)))), ((int)(((byte)(140)))), ((int)(((byte)(140)))));
            this.lblOrganization.Location = new System.Drawing.Point(29, 110);
            this.lblOrganization.Name = "lblOrganization";
            this.lblOrganization.Size = new System.Drawing.Size(111, 20);
            this.lblOrganization.TabIndex = 6;
            this.lblOrganization.Text = "Organization";
            // 
            // txtWebsite
            // 
            this.txtWebsite.AcceptsReturn = false;
            this.txtWebsite.AcceptsTab = false;
            this.txtWebsite.AnimationSpeed = 200;
            this.txtWebsite.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtWebsite.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtWebsite.AutoSizeHeight = true;
            this.txtWebsite.BackColor = System.Drawing.Color.Transparent;
            this.txtWebsite.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtWebsite.BackgroundImage")));
            this.txtWebsite.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            this.txtWebsite.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtWebsite.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            this.txtWebsite.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            this.txtWebsite.BorderRadius = 30;
            this.txtWebsite.BorderThickness = 2;
            this.txtWebsite.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtWebsite.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtWebsite.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtWebsite.DefaultText = "";
            this.txtWebsite.FillColor = System.Drawing.Color.White;
            this.txtWebsite.HideSelection = true;
            this.txtWebsite.IconLeft = null;
            this.txtWebsite.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtWebsite.IconPadding = 10;
            this.txtWebsite.IconRight = null;
            this.txtWebsite.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtWebsite.Lines = new string[0];
            this.txtWebsite.Location = new System.Drawing.Point(371, 310);
            this.txtWebsite.MaxLength = 32767;
            this.txtWebsite.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtWebsite.Modified = false;
            this.txtWebsite.Multiline = false;
            this.txtWebsite.Name = "txtWebsite";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtWebsite.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtWebsite.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtWebsite.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtWebsite.OnIdleState = stateProperties20;
            this.txtWebsite.Padding = new System.Windows.Forms.Padding(3);
            this.txtWebsite.PasswordChar = '\0';
            this.txtWebsite.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtWebsite.PlaceholderText = "";
            this.txtWebsite.ReadOnly = false;
            this.txtWebsite.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtWebsite.SelectedText = "";
            this.txtWebsite.SelectionLength = 0;
            this.txtWebsite.SelectionStart = 0;
            this.txtWebsite.ShortcutsEnabled = true;
            this.txtWebsite.Size = new System.Drawing.Size(300, 40);
            this.txtWebsite.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtWebsite.TabIndex = 17;
            this.txtWebsite.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtWebsite.TextMarginBottom = 0;
            this.txtWebsite.TextMarginLeft = 3;
            this.txtWebsite.TextMarginTop = 1;
            this.txtWebsite.TextPlaceholder = "";
            this.txtWebsite.UseSystemPasswordChar = false;
            this.txtWebsite.WordWrap = true;
            // 
            // lblWebsite
            // 
            this.lblWebsite.AutoSize = true;
            this.lblWebsite.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblWebsite.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(140)))), ((int)(((byte)(140)))), ((int)(((byte)(140)))));
            this.lblWebsite.Location = new System.Drawing.Point(371, 280);
            this.lblWebsite.Name = "lblWebsite";
            this.lblWebsite.Size = new System.Drawing.Size(74, 20);
            this.lblWebsite.TabIndex = 16;
            this.lblWebsite.Text = "Website";
            // 
            // txtEmail
            // 
            this.txtEmail.AcceptsReturn = false;
            this.txtEmail.AcceptsTab = false;
            this.txtEmail.AnimationSpeed = 200;
            this.txtEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtEmail.AutoSizeHeight = true;
            this.txtEmail.BackColor = System.Drawing.Color.Transparent;
            this.txtEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtEmail.BackgroundImage")));
            this.txtEmail.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            this.txtEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            this.txtEmail.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            this.txtEmail.BorderRadius = 30;
            this.txtEmail.BorderThickness = 2;
            this.txtEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtEmail.DefaultText = "";
            this.txtEmail.FillColor = System.Drawing.Color.White;
            this.txtEmail.HideSelection = true;
            this.txtEmail.IconLeft = null;
            this.txtEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.IconPadding = 10;
            this.txtEmail.IconRight = null;
            this.txtEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.Lines = new string[0];
            this.txtEmail.Location = new System.Drawing.Point(29, 310);
            this.txtEmail.MaxLength = 32767;
            this.txtEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtEmail.Modified = false;
            this.txtEmail.Multiline = false;
            this.txtEmail.Name = "txtEmail";
            stateProperties21.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtEmail.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnIdleState = stateProperties24;
            this.txtEmail.Padding = new System.Windows.Forms.Padding(3);
            this.txtEmail.PasswordChar = '\0';
            this.txtEmail.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtEmail.PlaceholderText = "";
            this.txtEmail.ReadOnly = false;
            this.txtEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtEmail.SelectedText = "";
            this.txtEmail.SelectionLength = 0;
            this.txtEmail.SelectionStart = 0;
            this.txtEmail.ShortcutsEnabled = true;
            this.txtEmail.Size = new System.Drawing.Size(300, 40);
            this.txtEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtEmail.TabIndex = 15;
            this.txtEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtEmail.TextMarginBottom = 0;
            this.txtEmail.TextMarginLeft = 3;
            this.txtEmail.TextMarginTop = 1;
            this.txtEmail.TextPlaceholder = "";
            this.txtEmail.UseSystemPasswordChar = false;
            this.txtEmail.WordWrap = true;
            // 
            // lblEmail
            // 
            this.lblEmail.AutoSize = true;
            this.lblEmail.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblEmail.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(140)))), ((int)(((byte)(140)))), ((int)(((byte)(140)))));
            this.lblEmail.Location = new System.Drawing.Point(29, 280);
            this.lblEmail.Name = "lblEmail";
            this.lblEmail.Size = new System.Drawing.Size(53, 20);
            this.lblEmail.TabIndex = 14;
            this.lblEmail.Text = "Email";
            // 
            // txtPhonePrivate
            // 
            this.txtPhonePrivate.AcceptsReturn = false;
            this.txtPhonePrivate.AcceptsTab = false;
            this.txtPhonePrivate.AnimationSpeed = 200;
            this.txtPhonePrivate.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPhonePrivate.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPhonePrivate.AutoSizeHeight = true;
            this.txtPhonePrivate.BackColor = System.Drawing.Color.Transparent;
            this.txtPhonePrivate.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPhonePrivate.BackgroundImage")));
            this.txtPhonePrivate.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            this.txtPhonePrivate.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPhonePrivate.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            this.txtPhonePrivate.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            this.txtPhonePrivate.BorderRadius = 30;
            this.txtPhonePrivate.BorderThickness = 2;
            this.txtPhonePrivate.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPhonePrivate.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhonePrivate.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtPhonePrivate.DefaultText = "";
            this.txtPhonePrivate.FillColor = System.Drawing.Color.White;
            this.txtPhonePrivate.HideSelection = true;
            this.txtPhonePrivate.IconLeft = null;
            this.txtPhonePrivate.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhonePrivate.IconPadding = 10;
            this.txtPhonePrivate.IconRight = null;
            this.txtPhonePrivate.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhonePrivate.Lines = new string[0];
            this.txtPhonePrivate.Location = new System.Drawing.Point(371, 225);
            this.txtPhonePrivate.MaxLength = 32767;
            this.txtPhonePrivate.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPhonePrivate.Modified = false;
            this.txtPhonePrivate.Multiline = false;
            this.txtPhonePrivate.Name = "txtPhonePrivate";
            stateProperties25.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhonePrivate.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPhonePrivate.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhonePrivate.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhonePrivate.OnIdleState = stateProperties28;
            this.txtPhonePrivate.Padding = new System.Windows.Forms.Padding(3);
            this.txtPhonePrivate.PasswordChar = '\0';
            this.txtPhonePrivate.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtPhonePrivate.PlaceholderText = "";
            this.txtPhonePrivate.ReadOnly = false;
            this.txtPhonePrivate.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPhonePrivate.SelectedText = "";
            this.txtPhonePrivate.SelectionLength = 0;
            this.txtPhonePrivate.SelectionStart = 0;
            this.txtPhonePrivate.ShortcutsEnabled = true;
            this.txtPhonePrivate.Size = new System.Drawing.Size(300, 40);
            this.txtPhonePrivate.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPhonePrivate.TabIndex = 13;
            this.txtPhonePrivate.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPhonePrivate.TextMarginBottom = 0;
            this.txtPhonePrivate.TextMarginLeft = 3;
            this.txtPhonePrivate.TextMarginTop = 1;
            this.txtPhonePrivate.TextPlaceholder = "";
            this.txtPhonePrivate.UseSystemPasswordChar = false;
            this.txtPhonePrivate.WordWrap = true;
            // 
            // lblPhonePrivate
            // 
            this.lblPhonePrivate.AutoSize = true;
            this.lblPhonePrivate.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblPhonePrivate.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(140)))), ((int)(((byte)(140)))), ((int)(((byte)(140)))));
            this.lblPhonePrivate.Location = new System.Drawing.Point(371, 195);
            this.lblPhonePrivate.Name = "lblPhonePrivate";
            this.lblPhonePrivate.Size = new System.Drawing.Size(132, 20);
            this.lblPhonePrivate.TabIndex = 12;
            this.lblPhonePrivate.Text = "Phone (Private)";
            // 
            // txtPhoneWork
            // 
            this.txtPhoneWork.AcceptsReturn = false;
            this.txtPhoneWork.AcceptsTab = false;
            this.txtPhoneWork.AnimationSpeed = 200;
            this.txtPhoneWork.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPhoneWork.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPhoneWork.AutoSizeHeight = true;
            this.txtPhoneWork.BackColor = System.Drawing.Color.Transparent;
            this.txtPhoneWork.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPhoneWork.BackgroundImage")));
            this.txtPhoneWork.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            this.txtPhoneWork.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPhoneWork.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            this.txtPhoneWork.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            this.txtPhoneWork.BorderRadius = 30;
            this.txtPhoneWork.BorderThickness = 2;
            this.txtPhoneWork.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPhoneWork.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhoneWork.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtPhoneWork.DefaultText = "";
            this.txtPhoneWork.FillColor = System.Drawing.Color.White;
            this.txtPhoneWork.HideSelection = true;
            this.txtPhoneWork.IconLeft = null;
            this.txtPhoneWork.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhoneWork.IconPadding = 10;
            this.txtPhoneWork.IconRight = null;
            this.txtPhoneWork.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhoneWork.Lines = new string[0];
            this.txtPhoneWork.Location = new System.Drawing.Point(29, 225);
            this.txtPhoneWork.MaxLength = 32767;
            this.txtPhoneWork.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPhoneWork.Modified = false;
            this.txtPhoneWork.Multiline = false;
            this.txtPhoneWork.Name = "txtPhoneWork";
            stateProperties29.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhoneWork.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPhoneWork.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhoneWork.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhoneWork.OnIdleState = stateProperties32;
            this.txtPhoneWork.Padding = new System.Windows.Forms.Padding(3);
            this.txtPhoneWork.PasswordChar = '\0';
            this.txtPhoneWork.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtPhoneWork.PlaceholderText = "";
            this.txtPhoneWork.ReadOnly = false;
            this.txtPhoneWork.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPhoneWork.SelectedText = "";
            this.txtPhoneWork.SelectionLength = 0;
            this.txtPhoneWork.SelectionStart = 0;
            this.txtPhoneWork.ShortcutsEnabled = true;
            this.txtPhoneWork.Size = new System.Drawing.Size(300, 40);
            this.txtPhoneWork.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPhoneWork.TabIndex = 11;
            this.txtPhoneWork.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPhoneWork.TextMarginBottom = 0;
            this.txtPhoneWork.TextMarginLeft = 3;
            this.txtPhoneWork.TextMarginTop = 1;
            this.txtPhoneWork.TextPlaceholder = "";
            this.txtPhoneWork.UseSystemPasswordChar = false;
            this.txtPhoneWork.WordWrap = true;
            // 
            // lblPhoneWork
            // 
            this.lblPhoneWork.AutoSize = true;
            this.lblPhoneWork.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblPhoneWork.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(140)))), ((int)(((byte)(140)))), ((int)(((byte)(140)))));
            this.lblPhoneWork.Location = new System.Drawing.Point(29, 195);
            this.lblPhoneWork.Name = "lblPhoneWork";
            this.lblPhoneWork.Size = new System.Drawing.Size(118, 20);
            this.lblPhoneWork.TabIndex = 10;
            this.lblPhoneWork.Text = "Phone (Work)";
            // 
            // txtZipcode
            // 
            this.txtZipcode.AcceptsReturn = false;
            this.txtZipcode.AcceptsTab = false;
            this.txtZipcode.AnimationSpeed = 200;
            this.txtZipcode.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtZipcode.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtZipcode.AutoSizeHeight = true;
            this.txtZipcode.BackColor = System.Drawing.Color.Transparent;
            this.txtZipcode.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtZipcode.BackgroundImage")));
            this.txtZipcode.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            this.txtZipcode.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtZipcode.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            this.txtZipcode.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            this.txtZipcode.BorderRadius = 30;
            this.txtZipcode.BorderThickness = 2;
            this.txtZipcode.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtZipcode.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtZipcode.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtZipcode.DefaultText = "";
            this.txtZipcode.FillColor = System.Drawing.Color.White;
            this.txtZipcode.HideSelection = true;
            this.txtZipcode.IconLeft = null;
            this.txtZipcode.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtZipcode.IconPadding = 10;
            this.txtZipcode.IconRight = null;
            this.txtZipcode.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtZipcode.Lines = new string[0];
            this.txtZipcode.Location = new System.Drawing.Point(371, 480);
            this.txtZipcode.MaxLength = 32767;
            this.txtZipcode.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtZipcode.Modified = false;
            this.txtZipcode.Multiline = false;
            this.txtZipcode.Name = "txtZipcode";
            stateProperties33.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtZipcode.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtZipcode.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtZipcode.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtZipcode.OnIdleState = stateProperties36;
            this.txtZipcode.Padding = new System.Windows.Forms.Padding(3);
            this.txtZipcode.PasswordChar = '\0';
            this.txtZipcode.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtZipcode.PlaceholderText = "";
            this.txtZipcode.ReadOnly = false;
            this.txtZipcode.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtZipcode.SelectedText = "";
            this.txtZipcode.SelectionLength = 0;
            this.txtZipcode.SelectionStart = 0;
            this.txtZipcode.ShortcutsEnabled = true;
            this.txtZipcode.Size = new System.Drawing.Size(300, 40);
            this.txtZipcode.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtZipcode.TabIndex = 25;
            this.txtZipcode.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtZipcode.TextMarginBottom = 0;
            this.txtZipcode.TextMarginLeft = 3;
            this.txtZipcode.TextMarginTop = 1;
            this.txtZipcode.TextPlaceholder = "";
            this.txtZipcode.UseSystemPasswordChar = false;
            this.txtZipcode.WordWrap = true;
            // 
            // lblZipcode
            // 
            this.lblZipcode.AutoSize = true;
            this.lblZipcode.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblZipcode.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(140)))), ((int)(((byte)(140)))), ((int)(((byte)(140)))));
            this.lblZipcode.Location = new System.Drawing.Point(371, 450);
            this.lblZipcode.Name = "lblZipcode";
            this.lblZipcode.Size = new System.Drawing.Size(73, 20);
            this.lblZipcode.TabIndex = 24;
            this.lblZipcode.Text = "Zipcode";
            // 
            // txtCity
            // 
            this.txtCity.AcceptsReturn = false;
            this.txtCity.AcceptsTab = false;
            this.txtCity.AnimationSpeed = 200;
            this.txtCity.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCity.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCity.AutoSizeHeight = true;
            this.txtCity.BackColor = System.Drawing.Color.Transparent;
            this.txtCity.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCity.BackgroundImage")));
            this.txtCity.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            this.txtCity.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCity.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            this.txtCity.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            this.txtCity.BorderRadius = 30;
            this.txtCity.BorderThickness = 2;
            this.txtCity.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCity.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCity.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtCity.DefaultText = "";
            this.txtCity.FillColor = System.Drawing.Color.White;
            this.txtCity.HideSelection = true;
            this.txtCity.IconLeft = null;
            this.txtCity.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCity.IconPadding = 10;
            this.txtCity.IconRight = null;
            this.txtCity.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCity.Lines = new string[0];
            this.txtCity.Location = new System.Drawing.Point(29, 480);
            this.txtCity.MaxLength = 32767;
            this.txtCity.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCity.Modified = false;
            this.txtCity.Multiline = false;
            this.txtCity.Name = "txtCity";
            stateProperties37.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCity.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCity.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCity.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCity.OnIdleState = stateProperties40;
            this.txtCity.Padding = new System.Windows.Forms.Padding(3);
            this.txtCity.PasswordChar = '\0';
            this.txtCity.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtCity.PlaceholderText = "";
            this.txtCity.ReadOnly = false;
            this.txtCity.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCity.SelectedText = "";
            this.txtCity.SelectionLength = 0;
            this.txtCity.SelectionStart = 0;
            this.txtCity.ShortcutsEnabled = true;
            this.txtCity.Size = new System.Drawing.Size(300, 40);
            this.txtCity.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCity.TabIndex = 23;
            this.txtCity.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCity.TextMarginBottom = 0;
            this.txtCity.TextMarginLeft = 3;
            this.txtCity.TextMarginTop = 1;
            this.txtCity.TextPlaceholder = "";
            this.txtCity.UseSystemPasswordChar = false;
            this.txtCity.WordWrap = true;
            // 
            // lblCity
            // 
            this.lblCity.AutoSize = true;
            this.lblCity.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblCity.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(140)))), ((int)(((byte)(140)))), ((int)(((byte)(140)))));
            this.lblCity.Location = new System.Drawing.Point(29, 450);
            this.lblCity.Name = "lblCity";
            this.lblCity.Size = new System.Drawing.Size(39, 20);
            this.lblCity.TabIndex = 22;
            this.lblCity.Text = "City";
            // 
            // txtStreet
            // 
            this.txtStreet.AcceptsReturn = false;
            this.txtStreet.AcceptsTab = false;
            this.txtStreet.AnimationSpeed = 200;
            this.txtStreet.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtStreet.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtStreet.AutoSizeHeight = true;
            this.txtStreet.BackColor = System.Drawing.Color.Transparent;
            this.txtStreet.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtStreet.BackgroundImage")));
            this.txtStreet.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            this.txtStreet.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtStreet.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            this.txtStreet.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            this.txtStreet.BorderRadius = 30;
            this.txtStreet.BorderThickness = 2;
            this.txtStreet.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtStreet.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtStreet.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtStreet.DefaultText = "";
            this.txtStreet.FillColor = System.Drawing.Color.White;
            this.txtStreet.HideSelection = true;
            this.txtStreet.IconLeft = null;
            this.txtStreet.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtStreet.IconPadding = 10;
            this.txtStreet.IconRight = null;
            this.txtStreet.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtStreet.Lines = new string[0];
            this.txtStreet.Location = new System.Drawing.Point(371, 395);
            this.txtStreet.MaxLength = 32767;
            this.txtStreet.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtStreet.Modified = false;
            this.txtStreet.Multiline = false;
            this.txtStreet.Name = "txtStreet";
            stateProperties41.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtStreet.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtStreet.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtStreet.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            stateProperties44.FillColor = System.Drawing.Color.White;
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtStreet.OnIdleState = stateProperties44;
            this.txtStreet.Padding = new System.Windows.Forms.Padding(3);
            this.txtStreet.PasswordChar = '\0';
            this.txtStreet.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtStreet.PlaceholderText = "";
            this.txtStreet.ReadOnly = false;
            this.txtStreet.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtStreet.SelectedText = "";
            this.txtStreet.SelectionLength = 0;
            this.txtStreet.SelectionStart = 0;
            this.txtStreet.ShortcutsEnabled = true;
            this.txtStreet.Size = new System.Drawing.Size(300, 40);
            this.txtStreet.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtStreet.TabIndex = 21;
            this.txtStreet.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtStreet.TextMarginBottom = 0;
            this.txtStreet.TextMarginLeft = 3;
            this.txtStreet.TextMarginTop = 1;
            this.txtStreet.TextPlaceholder = "";
            this.txtStreet.UseSystemPasswordChar = false;
            this.txtStreet.WordWrap = true;
            // 
            // lblStreet
            // 
            this.lblStreet.AutoSize = true;
            this.lblStreet.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblStreet.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(140)))), ((int)(((byte)(140)))), ((int)(((byte)(140)))));
            this.lblStreet.Location = new System.Drawing.Point(371, 365);
            this.lblStreet.Name = "lblStreet";
            this.lblStreet.Size = new System.Drawing.Size(59, 20);
            this.lblStreet.TabIndex = 20;
            this.lblStreet.Text = "Street";
            // 
            // txtCountry
            // 
            this.txtCountry.AcceptsReturn = false;
            this.txtCountry.AcceptsTab = false;
            this.txtCountry.AnimationSpeed = 200;
            this.txtCountry.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCountry.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCountry.AutoSizeHeight = true;
            this.txtCountry.BackColor = System.Drawing.Color.Transparent;
            this.txtCountry.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCountry.BackgroundImage")));
            this.txtCountry.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            this.txtCountry.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCountry.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            this.txtCountry.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            this.txtCountry.BorderRadius = 30;
            this.txtCountry.BorderThickness = 2;
            this.txtCountry.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCountry.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCountry.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtCountry.DefaultText = "";
            this.txtCountry.FillColor = System.Drawing.Color.White;
            this.txtCountry.HideSelection = true;
            this.txtCountry.IconLeft = null;
            this.txtCountry.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCountry.IconPadding = 10;
            this.txtCountry.IconRight = null;
            this.txtCountry.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCountry.Lines = new string[0];
            this.txtCountry.Location = new System.Drawing.Point(29, 395);
            this.txtCountry.MaxLength = 32767;
            this.txtCountry.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCountry.Modified = false;
            this.txtCountry.Multiline = false;
            this.txtCountry.Name = "txtCountry";
            stateProperties45.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCountry.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties46.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties46.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCountry.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCountry.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(132)))), ((int)(((byte)(227)))));
            stateProperties48.FillColor = System.Drawing.Color.White;
            stateProperties48.ForeColor = System.Drawing.Color.Empty;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCountry.OnIdleState = stateProperties48;
            this.txtCountry.Padding = new System.Windows.Forms.Padding(3);
            this.txtCountry.PasswordChar = '\0';
            this.txtCountry.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtCountry.PlaceholderText = "";
            this.txtCountry.ReadOnly = false;
            this.txtCountry.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCountry.SelectedText = "";
            this.txtCountry.SelectionLength = 0;
            this.txtCountry.SelectionStart = 0;
            this.txtCountry.ShortcutsEnabled = true;
            this.txtCountry.Size = new System.Drawing.Size(300, 40);
            this.txtCountry.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCountry.TabIndex = 19;
            this.txtCountry.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCountry.TextMarginBottom = 0;
            this.txtCountry.TextMarginLeft = 3;
            this.txtCountry.TextMarginTop = 1;
            this.txtCountry.TextPlaceholder = "";
            this.txtCountry.UseSystemPasswordChar = false;
            this.txtCountry.WordWrap = true;
            // 
            // lblCountry
            // 
            this.lblCountry.AutoSize = true;
            this.lblCountry.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblCountry.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(140)))), ((int)(((byte)(140)))), ((int)(((byte)(140)))));
            this.lblCountry.Location = new System.Drawing.Point(29, 365);
            this.lblCountry.Name = "lblCountry";
            this.lblCountry.Size = new System.Drawing.Size(71, 20);
            this.lblCountry.TabIndex = 18;
            this.lblCountry.Text = "Country";
            // 
            // VCardPanel
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.Controls.Add(this.txtZipcode);
            this.Controls.Add(this.lblZipcode);
            this.Controls.Add(this.txtCity);
            this.Controls.Add(this.lblCity);
            this.Controls.Add(this.txtStreet);
            this.Controls.Add(this.lblStreet);
            this.Controls.Add(this.txtCountry);
            this.Controls.Add(this.lblCountry);
            this.Controls.Add(this.txtWebsite);
            this.Controls.Add(this.lblWebsite);
            this.Controls.Add(this.txtEmail);
            this.Controls.Add(this.lblEmail);
            this.Controls.Add(this.txtPhonePrivate);
            this.Controls.Add(this.lblPhonePrivate);
            this.Controls.Add(this.txtPhoneWork);
            this.Controls.Add(this.lblPhoneWork);
            this.Controls.Add(this.txtOrgTitle);
            this.Controls.Add(this.lblOrganizationTitle);
            this.Controls.Add(this.txtOrganization);
            this.Controls.Add(this.lblOrganization);
            this.Controls.Add(this.txtLastName);
            this.Controls.Add(this.lblLastName);
            this.Controls.Add(this.txtFirstName);
            this.Controls.Add(this.lblFirstName);
            this.Name = "VCardPanel";
            this.Size = new System.Drawing.Size(700, 570);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label lblFirstName;
        private Bunifu.UI.WinForms.BunifuTextBox txtFirstName;
        private System.Windows.Forms.Label lblLastName;
        private Bunifu.UI.WinForms.BunifuTextBox txtLastName;
        private Bunifu.UI.WinForms.BunifuTextBox txtOrgTitle;
        private System.Windows.Forms.Label lblOrganizationTitle;
        private Bunifu.UI.WinForms.BunifuTextBox txtOrganization;
        private System.Windows.Forms.Label lblOrganization;
        private Bunifu.UI.WinForms.BunifuTextBox txtWebsite;
        private System.Windows.Forms.Label lblWebsite;
        private Bunifu.UI.WinForms.BunifuTextBox txtEmail;
        private System.Windows.Forms.Label lblEmail;
        private Bunifu.UI.WinForms.BunifuTextBox txtPhonePrivate;
        private System.Windows.Forms.Label lblPhonePrivate;
        private Bunifu.UI.WinForms.BunifuTextBox txtPhoneWork;
        private System.Windows.Forms.Label lblPhoneWork;
        private Bunifu.UI.WinForms.BunifuTextBox txtZipcode;
        private System.Windows.Forms.Label lblZipcode;
        private Bunifu.UI.WinForms.BunifuTextBox txtCity;
        private System.Windows.Forms.Label lblCity;
        private Bunifu.UI.WinForms.BunifuTextBox txtStreet;
        private System.Windows.Forms.Label lblStreet;
        private Bunifu.UI.WinForms.BunifuTextBox txtCountry;
        private System.Windows.Forms.Label lblCountry;
    }
}
